"""The paths the artifact cycle, the gate wrappers, and the interactive entry points write to or delete, and the two green-finish switches, in a module that imports nothing from the repo.

The paths are the green records each keyed stage skips on, the cycle summary, the run_m1 and conform summaries the driver unlinks before it spawns those steps, and the build-log root each pass creates a run directory under. The autouse fixture `_redirect_cycle_writes` in `rebuild/conftest.py` points them under `tmp_path` for every rebuild test, except the deep sweep and deep replay green records, which the tests that use them redirect. Writers read them as `cycle_paths.RUN_M1_GREEN` at call time, never through a copy bound at import or in a default argument, so the redirect reaches every write. `REBUILD_GATE_EXEMPT_PREFIXES` is here because the same conftest derives its forbidden trees from it.

The module imports nothing from the repo because `closure_of` in `rebuild.tools.contracts_closure` adds both conftests' static import closures to every test's closure. A conftest that imported the cycle driver to patch these paths would put rebuild/pipeline/ and rebuild/review/ into every closure, and no pipeline edit could let a test be skipped. `rebuild/test_contracts_closure.py` checks the conftests' imports.

`RETENTION_ENABLED` and `READINESS_ENABLED` switch off the two green-finish stages whose targets come from the live tree, not from a path here. The retention pass prunes the root's carried exports, autosave stashes, and verdict journal, and the readiness checklist reads the served surface and the root autosave. The rebuild suite sets both to False so a test that reaches a green finish leaves the live repo alone. `_finish` in `artifact_cycle` reads both at call time, so a test that checks either stage sets its switch back to True and patches the callable.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
M1_OUT = ROOT / "rebuild" / "out" / "m1"
CYCLE_SUMMARY = ROOT / "rebuild" / "out" / "cycle_summary.json"
MAKE_TEST_GREEN = ROOT / "rebuild" / "out" / "make-test-green.json"
PYRIGHT_GREEN = ROOT / "rebuild" / "out" / "pyright-green.json"
RUN_M1_GREEN = ROOT / "rebuild" / "out" / "run-m1-green.json"
CONFORM_GREEN = ROOT / "rebuild" / "out" / "conform-green.json"
DEEP_SWEEP_GREEN = ROOT / "rebuild" / "out" / "deep-sweep-green.json"
DEEP_REPLAY_GREEN = ROOT / "rebuild" / "out" / "deep-replay-green.json"
REBUILD_CONTRACTS_GREEN = ROOT / "rebuild" / "out" / "rebuild-contracts-green.json"
PLUMBING_GREEN = ROOT / "rebuild" / "out" / "plumbing-green.json"
# Each pass writes its step logs under BUILD_LOGS_ROOT, and the green-finish retention pass keeps the newest BUILD_LOGS_KEEP run directories. Ten is about a working week of passes, and every run's logs can be regenerated by running the pass again.
BUILD_LOGS_ROOT = ROOT / "var" / "build-logs"
BUILD_LOGS_KEEP = 10

M1_SUMMARY_FILES = {
    "pipeline": M1_OUT / "pipeline_summary.json",
    "manual_pins": M1_OUT / "manual_pins_summary.json",
    "oracle": M1_OUT / "oracle_summary.json",
}
CONFORM_SUMMARY = M1_OUT / "conform_summary.json"

REBUILD_GATE_EXEMPT_PREFIXES = (
    "rebuild/evidence/",
    "rebuild/review/jstests/",
    "rebuild/review-census-pins.json",
    "rebuild/m1-contact-allow.yaml",
)

RETENTION_ENABLED = True
READINESS_ENABLED = True
