default_install_hook_types: [pre-push]
default_stages: [pre-push]

repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.0
    hooks:
      - id: black
        args: [--check]
