default_install_hook_types: [pre-push]
default_stages: [pre-push]

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: uv run black --check
        language: system
        types_or: [python, pyi]
