"""Why the compilers land where they do: the settlement kernel's inner loop is dominated by constructing and hashing small frozen dataclasses (model.CellId, settle.RightToken/Candidate). This measures exactly that, three ways, with every result forced to escape into a dict so no compiler can delete the allocation.

`Frozen` is the repo's shape verbatim. `Handwritten` is the same class with `__init__` / `__hash__` / `__eq__` written out by hand instead of generated by `@dataclass` — the question being whether an accelerator can reach the generated dunders at all. `tuple_keys` is the packed-representation floor a Rust or Go port would start from.
"""

from __future__ import annotations

from dataclasses import dataclass

RUNES = ("qsAh", "qsDay", "qsFee", "qsIt", "qsMay", "qsPea", "qsSee", "qsUtter")
STANCES = ("hapax", "entry_baseline", "entry_xheight", "exit_baseline")
HEIGHTS = (None, "x-height", "baseline", "mid")


@dataclass(frozen=True)
class Frozen:
    rune: str
    stance: str
    entry: str | None
    exit: str | None
    extension: int


class Handwritten:
    __slots__ = ("rune", "stance", "entry", "exit", "extension")

    def __init__(self, rune: str, stance: str, entry: str | None, exit: str | None, extension: int) -> None:
        self.rune = rune
        self.stance = stance
        self.entry = entry
        self.exit = exit
        self.extension = extension

    def __hash__(self) -> int:
        return hash((self.rune, self.stance, self.entry, self.exit, self.extension))

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Handwritten):
            return NotImplemented
        return (
            self.rune == other.rune
            and self.stance == other.stance
            and self.entry == other.entry
            and self.exit == other.exit
            and self.extension == other.extension
        )


def frozen_memo(n: int) -> int:
    """Build a memo keyed by the frozen dataclass, exactly as transition_trace keys its cache."""
    memo: dict[Frozen, int] = {}
    acc = 0
    for i in range(n):
        key = Frozen(RUNES[i % 8], STANCES[i % 4], HEIGHTS[i % 4], HEIGHTS[(i + 1) % 4], i % 3)
        hit = memo.get(key)
        if hit is None:
            memo[key] = i
            acc += 1
        else:
            acc += hit & 1
    return acc * 1000003 + len(memo)


def handwritten_memo(n: int) -> int:
    memo: dict[Handwritten, int] = {}
    acc = 0
    for i in range(n):
        key = Handwritten(RUNES[i % 8], STANCES[i % 4], HEIGHTS[i % 4], HEIGHTS[(i + 1) % 4], i % 3)
        hit = memo.get(key)
        if hit is None:
            memo[key] = i
            acc += 1
        else:
            acc += hit & 1
    return acc * 1000003 + len(memo)


def tuple_memo(n: int) -> int:
    memo: dict[tuple, int] = {}
    acc = 0
    for i in range(n):
        key = (RUNES[i % 8], STANCES[i % 4], HEIGHTS[i % 4], HEIGHTS[(i + 1) % 4], i % 3)
        hit = memo.get(key)
        if hit is None:
            memo[key] = i
            acc += 1
        else:
            acc += hit & 1
    return acc * 1000003 + len(memo)
