#import "style.typ": *

#include "chapters/00-introduction.typ"
#include "chapters/01-what-is-quikscript.typ"
#include "chapters/02-what-is-a-font-actually.typ"
#include "chapters/03-the-pixel-grid.typ"
#include "chapters/04-how-letters-join-the-concept.typ"
#include "chapters/05-glyph-variants.typ"
#include "chapters/06-feature-files-and-pipeline.typ"
#include "chapters/07-gsub-substituting-the-right-glyph.typ"
#include "chapters/08-gpos-positioning-joined-glyphs.typ"
#include "chapters/09-padding-and-spacing-refinements.typ"
#include "chapters/10-the-three-font-variants.typ"
#include "chapters/11-worked-example.typ"
#include "chapters/12-appendix-yaml-schema.typ"
