"""Shared frozen dataclasses for the M1 pipeline (rebuild/M1-PLAN.md section 5): `ResolvedSpec` and the runes, stances, surfaces, and policy records under it, `CellId` and `Settled`, `CellPlan` (from `surface.resolve_cell`), and `GlyphRecord` (from `geometry.realize`).

`kernel_io` serializes a `ResolvedSpec` from these field definitions, and the Rust crate lists the same fields by hand (`rebuild/kernel-rs/src/model.rs` and `parse.rs`). A change here must also be made in the crate; the spec-echo test in `rebuild/test_kernel_io.py` fails until it is.

The adjustment tokens in `CellId.adjustments` are generated by settlement and read by geometry, never authored, and their order matters:

- `locked`: the ZWNJ chokepoint twin, with the entry side removed.
- `en-ext-N` / `ex-ext-N`: lengthen the connector on the named side by N pixels in the same row.
- `en-con-N` / `ex-con-N`: shorten it by N pixels.
- `en-trim-N` / `ex-trim-N`: receiver-side removal of N pixels of same-row ink that leaves the anchor in place, which exempts that side from the anchor convention.
- `en-bind-<bitmap>` / `ex-bind-<bitmap>`: a `bind:` extend or contract that substitutes a named hand-drawn sibling bitmap. An extend writes its bind token before its `ext` token, because geometry applies tokens in order and lengthens the drawing the binding put in place.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Collection, Literal, Mapping

Height = str  # "baseline" | "x-height" | "y6" | "top" (registry-validated)

NONE_STATE = "none"
WITHDRAWN_SUFFIX = "-withdrawn"

RIGHT_WINDOW_SLOTS = 4  # right1..rightN, the raw window settlement sees. table.py checks its Transition and Rule slot counts against this at import, so raising the chain cap without widening the table fails at import instead of emitting records that read past the window.
RIGHT_CHAIN_CAP = (
    RIGHT_WINDOW_SLOTS - 1
)  # the most then: hops past the immediate right neighbor that spec_load's lint allows, counting hops inside except: entries; derived from the window size


@dataclass(frozen=True, slots=True)
class CellId:
    rune: str  # family name (ligatures are ordinary runes)
    stance: str
    entry: Height | None
    exit: Height | None
    adjustments: tuple[str, ...] = ()  # ordered, generated: ("en-ext-1",), ("locked",), () — never authored


@dataclass(frozen=True, slots=True)
class Settled:
    cell: CellId
    seam: Height | None  # the committed seam toward the next position
    extension: int  # summed connector pixels carried on this seam by this side


@dataclass(frozen=True)
class Provenance:
    file: str
    path: str

    def __str__(self) -> str:
        return f"{self.file}:{self.path}"


@dataclass(frozen=True)
class Condition:
    """One side of a `when:` — the closed static vocabulary of design section 3.4. Axis values are tuples even when authored as scalars; empty tuple means the axis is unconstrained."""

    family: tuple[str, ...] = ()
    klass: tuple[str, ...] = ()  # predicate classes or rune-local groups ("class:" in YAML)
    stance: tuple[str, ...] = ()
    joined_at: Height | None = None  # the height of the join being decided; "none" = the seam did not join
    stroke: str | None = None
    is_token: str | None = None  # "boundary" | "space" | "zwnj" | "namer-dot" ("is:" in YAML)
    except_: tuple["Condition", ...] = ()
    then: "Condition | None" = None  # right-only static hop, lint-capped chain; forbidden on refuse records


@dataclass(frozen=True)
class When:
    left: Condition | None = None
    right: Condition | None = None
    self_entry: str | None = None  # "live" | "none"
    self_exit: str | None = None
    word: str | None = None  # "initial" | "medial" | "final" | "isolated"
    feature: str | None = None


@dataclass(frozen=True)
class Stub:
    """Same-row attachment ink at a side's anchor row (design section 3.2). `inks_when` names the state in which the columns are inked. `joined` is a connector nub that is blank in the base drawing and inked when the side joins. `withdrawn` is ink in the base drawing that is removed when the side joins, as in qsGay."""

    cols: tuple[int, ...]
    inks_when: str  # "joined" | "withdrawn"


@dataclass(frozen=True)
class SurfaceRow:
    """One entry or exit row: a height, an anchor x, and the optional bindings, scopes, and exceptions."""

    height: Height
    x: int
    stroke: str | None = None
    joined: str | None = None  # named sibling bitmap used when this side is live
    joined_x: int | None = None  # per-row anchor override that travels with the joined binding
    withdrawal: str | None = None  # named sibling bitmap, or "safe" (compiler-verified no reaching ink)
    stub: Stub | None = None
    scope: tuple[Condition, ...] = ()  # `from:` on entries, `toward:` on exits; empty = unscoped
    selectable: bool = (
        True  # False: settlement never selects this entry, and its anchor is kept for GPOS only (CellPlan.entry_curs_only)
    )
    ink_y: int | None = (
        None  # the old font's exit_ink_y: the row where the anchor and seam-gap checks read the exit's ink when the exit anchor sits off the stroke's row
    )
    x_off_convention: bool = False
    provenance: Provenance | None = None


@dataclass(frozen=True)
class Pairing:
    entry: str  # a height or "none"
    exit: str


@dataclass(frozen=True)
class Pairings:
    never: tuple[Pairing, ...] = ()
    only: tuple[Pairing, ...] | None = None


@dataclass(frozen=True)
class CellBinding:
    """An explicit `cells:` row: the named composition when side bindings touch one cell. `entry`/`exit` are state tokens: a height, a height plus "-withdrawn", or "none"."""

    entry: str
    exit: str
    bitmap: str
    entry_x: int | None = None
    exit_x: int | None = None
    provenance: Provenance | None = None


@dataclass(frozen=True)
class Unlock:
    feature: str
    entry: Height | None = None
    exit: Height | None = None
    pairing: Pairing | None = None
    when: When | None = None
    why: str | None = None
    provenance: Provenance | None = None


@dataclass(frozen=True)
class Surface:
    entries: Mapping[Height, SurfaceRow] = field(default_factory=dict)
    exits: Mapping[Height, SurfaceRow] = field(default_factory=dict)
    pairings: Pairings = field(default_factory=Pairings)
    cells: tuple[CellBinding, ...] = ()
    unlocks: tuple[Unlock, ...] = ()
    require: tuple[str, ...] = ()  # ("entry",) / ("exit",) for join-born stances


@dataclass(frozen=True)
class Bitmap:
    rows: tuple[str, ...]
    y_offset: int = 0

    @property
    def width(self) -> int:
        return max((len(row) for row in self.rows), default=0)

    def row_for_y(self, y: int) -> str | None:
        """The bitmap row at glyph-space y, or None when y is outside the drawing."""
        index = len(self.rows) - 1 - (y - self.y_offset)
        if 0 <= index < len(self.rows):
            return self.rows[index]
        return None


@dataclass(frozen=True)
class Stance:
    name: str
    motion: str
    traits: tuple[str, ...] = ()
    bitmap: Bitmap = field(default_factory=lambda: Bitmap(()))
    bitmaps: Mapping[str, Bitmap] = field(default_factory=dict)
    surface: Surface = field(default_factory=Surface)


@dataclass(frozen=True)
class PolicyRecord:
    """One rider (refuse, prefer, extend, contract, or resolve), in the record shape of design section 3.3. `id` lets a resolve's `against:` name the record. `against`, `pick`, and `migrated` are used only by resolve records (design section 5.8)."""

    kind: str
    when: When = field(default_factory=When)
    id: str | None = None
    stance: str | None = None
    entry: Height | None = None
    exit: Height | None = None
    cell: Mapping[str, str] | None = None  # cell-grain prefer target
    over: Mapping[str, str] | None = None
    mode: str | None = None  # prefer: "yields-to-joins" (default) | "absolute"
    by: int | None = None
    ok: tuple[int, int] | None = None
    bind: str | None = None
    trim: int | None = None
    split: tuple[int, int] | None = None
    against: tuple[str, str | None] | None = None  # (rune, record id) the resolve arbitrates against
    pick: Mapping[str, str] | None = (
        None  # the winning cell pattern (or {stance: ...}) at the conflicted window
    )
    migrated: str | None = None
    why: str | None = None
    provenance: Provenance | None = None


@dataclass(frozen=True)
class Policy:
    order: tuple[str, ...] = ()
    refuse: tuple[PolicyRecord, ...] = ()
    prefer: tuple[PolicyRecord, ...] = ()
    extend: tuple[PolicyRecord, ...] = ()
    contract: tuple[PolicyRecord, ...] = ()
    resolve: tuple[PolicyRecord, ...] = ()
    groups: Mapping[str, frozenset[str]] = field(default_factory=dict)  # membership resolved by spec_load


@dataclass(frozen=True)
class Rune:
    name: str
    codepoint: int | None = None
    sequence: tuple[str, ...] | None = None  # ligature runes declare this instead of a codepoint
    ductus: Mapping[str, str] = field(default_factory=dict)  # motion name -> hand-drawing prose
    notes: str | None = None
    mono: Bitmap | None = None
    stances: Mapping[str, Stance] = field(default_factory=dict)
    policy: Policy = field(default_factory=Policy)

    @property
    def default_stance(self) -> str:
        if self.policy.order:
            return self.policy.order[0]
        return next(iter(self.stances))


@dataclass(frozen=True)
class BoundaryToken:
    codepoint: int
    splits_runs: bool


@dataclass(frozen=True)
class FeatureInfo:
    kind: str  # "capability" | "taste"
    description: str = ""
    overlay: str | None = None


@dataclass(frozen=True)
class FamilyInfo:
    codepoint: int | None = None
    sequence: tuple[str, ...] | None = None


@dataclass(frozen=True)
class ScriptRegistry:
    heights: Mapping[Height, int] = field(default_factory=dict)
    boundary_tokens: Mapping[str, BoundaryToken] = field(default_factory=dict)
    features: Mapping[str, FeatureInfo] = field(default_factory=dict)
    interactions: tuple[tuple[str, ...], ...] = ()
    predicate_classes: Mapping[str, frozenset[str]] = field(default_factory=dict)  # membership resolved
    families: Mapping[str, FamilyInfo] = field(default_factory=dict)

    def y_of(self, height: Height) -> int:
        return self.heights[height]


@dataclass(frozen=True)
class ResolvedSpec:  # spec_load's output; the input to everything else
    runes: Mapping[str, Rune]  # only the modeled runes
    registry: ScriptRegistry


@dataclass(frozen=True)
class CellPlan:
    """`surface.resolve_cell`'s output: the resolved bindings for one cell. It names a bitmap but holds no ink. `bitmap` is the named sibling the cell is drawn with (None means the stance's base drawing). Anchor x values already include overrides. `safety_checks` lists the (side, height) pairs whose `withdrawal: safe` claim `defects.py` must verify. `convention_exempt` names the sides ("entry", "exit") whose declared row sets `x_off_convention`, so E-ANCHOR skips those sides only."""

    cell: CellId
    bitmap: str | None = None
    entry_x: int | None = None
    exit_x: int | None = None
    entry_stub: Stub | None = None
    exit_stub: Stub | None = None
    entry_curs_only: tuple[int, int] | None = None  # selectable: false anchor kept for GPOS parity
    exit_ink_y: int | None = None
    convention_exempt: tuple[str, ...] = ()
    safety_checks: tuple[tuple[str, Height], ...] = ()
    unlock: Unlock | None = None  # set when the cell exists only via this unlock row

    @property
    def needs_safety_check(self) -> bool:
        return bool(self.safety_checks)


@dataclass(frozen=True)
class GlyphRecord:
    """`geometry.realize`'s output: one compiled glyph. Anchors are (x, y) in glyph-space pixels. `name` is the compiled glyph name. `run_m1` names each settled cell's glyph with `settle.cell_label` and fails on a label over `geometry.MAX_GLYPH_NAME_BYTES`. When no name is passed, `realize` uses `geometry.display_name`, which cuts a long name and appends a hash."""

    name: str
    bitmap: tuple[str, ...]
    y_offset: int = 0
    entry: tuple[int, int] | None = None
    exit: tuple[int, int] | None = None
    entry_curs_only: tuple[int, int] | None = None
    advance_width: int | None = None
    exit_ink_y: int | None = None
    convention_exempt: tuple[str, ...] = ()  # sides exempt from E-ANCHOR ("entry"/"exit")
    safety_checks: tuple[tuple[str, Height], ...] = ()
    provenance: str = ""


Adjustment = (
    tuple[Literal["locked"], None, None]
    | tuple[Literal["ext", "con", "trim"], str, int]
    | tuple[Literal["bind"], str, str]
)


def parse_adjustment(token: str) -> Adjustment:
    """Split an adjustments token into (operation, side, argument): ("locked", None, None), ("ext", "en", 1), ("bind", "ex", "pulled-back-stubless"). The return is a union discriminated on the operation, so a caller that rules out "locked" gets a non-optional side."""
    if token == "locked":
        return ("locked", None, None)
    side, _, rest = token.partition("-")
    if side not in ("en", "ex") or not rest:
        raise ValueError(f"unrecognized adjustments token: {token!r}")
    op, _, argument = rest.partition("-")
    if op in ("ext", "con", "trim"):
        return (op, side, int(argument))
    if op == "bind":
        return ("bind", side, argument)
    raise ValueError(f"unrecognized adjustments token: {token!r}")


def feature_config_token(features: Collection[str]) -> str:
    enabled = sorted(features)
    return "+".join(enabled) if enabled else "default"


def relevant_marker_features(rune: Rune) -> tuple[str, ...]:
    """Returns the stylistic sets named by this rune's unlock rows, which are the sets it has marker twins for. A policy record gated on a feature reads the neighbor's marker instead, so it adds nothing here."""
    features: set[str] = set()
    for stance in rune.stances.values():
        for unlock in stance.surface.unlocks:
            features.add(unlock.feature)
    return tuple(sorted(features))


def marker_glyph_name(rune_name: str, active: Collection[str]) -> str:
    """Returns the marker-twin name for a rune under the active relevant features, or the bare name when none are active. Several sets are joined in sorted order: ss02+ss03 gives qsTea.ss02_ss03."""
    enabled = sorted(active)
    if not enabled:
        return rune_name
    return f"{rune_name}.{'_'.join(enabled)}"


def locked_glyph_name(raw_name: str) -> str:
    """Returns the name of the ZWNJ chokepoint twin of a raw input glyph (a bare rune or a marker twin)."""
    return f"{raw_name}.noentry"


def raw_rename_map(spec: ResolvedSpec | None, features: frozenset[str]) -> dict[str, str]:
    """Returns the marker fold for a configuration, the renaming of raw labels to marker twins: each rune whose unlock rows name an active set maps to its marker twin, and its chokepoint twin maps to the marker's chokepoint twin. The marker lookups rename every occurrence of such a rune before settlement runs, so settlement never sees its bare label. Returns an empty map when `spec` is None."""
    renames: dict[str, str] = {}
    if spec is None:
        return renames
    for rune_name, rune in spec.runes.items():
        relevant = frozenset(relevant_marker_features(rune)) & features
        if not relevant:
            continue
        marker = marker_glyph_name(rune_name, relevant)
        renames[rune_name] = marker
        renames[locked_glyph_name(rune_name)] = locked_glyph_name(marker)
    return renames


def isolated_overlay_active(spec: ResolvedSpec, features: Collection[str]) -> bool:
    """Returns whether any active feature is registered with `overlay: isolated` (ss10). Under such a feature the emitted font replaces every letter's cmap glyph with its anchor-free `.ss10` twin before formation, so no ligature forms, nothing settles, and every seam is a break. Such a configuration has no settlement table, and consumers use the isolated stream instead (`settle.isolated_overlay_settled`)."""
    return any(
        spec.registry.features.get(feature) is not None
        and spec.registry.features[feature].overlay == "isolated"
        for feature in features
    )


SS10_TWIN_SUFFIX = ".ss10"


def ss10_twin_name(raw_name: str) -> str:
    """Returns the name of the ss10 twin of a letter's raw cmap glyph. The twin is drawn like the bare glyph but has no cursive anchors and no cmap entry, and no formation, marker, chokepoint, or settlement lookup takes it as input. Substituting it before formation therefore keeps the letter out of every join: no ligature forms, nothing settles, and each letter stays its own cluster."""
    return f"{raw_name}{SS10_TWIN_SUFFIX}"
