"""The approved-snapshot isolation-leak gate.

Background: `test/test_isolation_leaks.py::test_no_visible_isolation_leaks` asserts that the depth-3 sweep finds zero visible leaks. But contextual `calt` rules chain across ≈600 lookups, so a leak can need four or more letters of context to surface — and a deeper sweep (`find_leaks(max_len=4)`) currently finds hundreds the depth-3 gate never sees. Chasing those by hand-writing letter tuples is the `44^n` treadmill the rest of `doc/leak-investigation-findings.md` is about.

This module replaces hand-enumeration with a golden snapshot. We capture the complete set of depth-4 visible leaks as stable structural signatures and check the live build against it:

  * a signature in the live build but NOT approved -> a regression (a change introduced a cross-break shape difference); the gate fails.
  * an approved signature that is NO LONGER live -> a leak you fixed; the gate fails so you re-bless the (now shorter) snapshot.

So the snapshot doubles as a to-do list: every line is a known leak, and shrinking the file is progress. Review sees exactly which cross-break interactions changed — no tuples to write.

Regenerate (bless the current state) with `make leak-snapshot`; check with `make test-leaks`.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEST_DIR = ROOT / "test"
SNAPSHOT_PATH = TEST_DIR / "isolation-leak-snapshot.txt"

if str(TEST_DIR) not in sys.path:
    sys.path.insert(0, str(TEST_DIR))
if str(ROOT / "tools") not in sys.path:
    sys.path.insert(0, str(ROOT / "tools"))

from build_check_html import IsolationLeakExample, Leak, _visual_status, find_leaks  # noqa: E402

# Depth 4 is the sweet spot: it surfaces the four-letter-context leaks the depth-3 gate misses, at ≈50 s (vs. ≈44x that for depth 5). It is a strong regression gate, not a completeness proof — see doc/leak-investigation-findings.md on why no fixed depth is provably complete.
MAX_LEN = 4

# A leak's structural identity, independent of which swept sequence happened to surface it first.
Signature = tuple[str, str, str, str]  # (isolated_left, left_chosen, isolated_right, right_chosen)


def _signature(leak: Leak) -> Signature:
    return (leak.isolated_left, leak.left_chosen, leak.isolated_right, leak.right_chosen)


def _example_label(example: IsolationLeakExample) -> str:
    fams = " ".join(f.removeprefix("qs") for f in example.families)
    return f"{fams} [break {example.break_index}]"


def current_leaks(max_len: int = MAX_LEN) -> dict[Signature, str]:
    """Map each live visible-leak signature to a stable, human-readable example label. `find_leaks` enumerates `itertools.product` in a fixed order, so the first example per signature is deterministic across runs."""
    out: dict[Signature, str] = {}
    for leak, example in find_leaks(max_len=max_len).items():
        if _visual_status(example) != "diff":
            continue
        sig = _signature(leak)
        if sig not in out:
            out[sig] = _example_label(example)
    return out


def _format_diff(leak_sig: Signature) -> str:
    # Both sides are always emitted (even the unchanged one) so the line round-trips back to the exact signature; a `*` marks the side that actually changed, for quick scanning.
    il, lc, ir, rc = leak_sig
    lmark = "*" if il != lc else " "
    rmark = "*" if ir != rc else " "
    return f"{lmark}L {il}->{lc} | {rmark}R {ir}->{rc}"


def format_snapshot(leaks: dict[Signature, str]) -> str:
    lines = [
        f"# Approved isolation leaks at depth {MAX_LEN}. Generated by `make leak-snapshot`; do not hand-edit.",
        "# Each line: <example sequence> [break N] :: <glyph diff>. See doc/leak-investigation-findings.md.",
        f"# count: {len(leaks)}",
        "",
    ]
    for sig in sorted(leaks):
        lines.append(f"{leaks[sig]} :: {_format_diff(sig)}")
    return "\n".join(lines) + "\n"


def parse_snapshot(text: str) -> dict[Signature, str]:
    """Reconstruct signatures from a snapshot file. Keyed identity is the glyph diff after `::`; the example label is informational."""
    leaks: dict[Signature, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        label, _, diff = line.partition(" :: ")
        sig = _parse_diff(diff)
        leaks[sig] = label.strip()
    return leaks


def _parse_diff(diff: str) -> Signature:
    il = lc = ir = rc = ""
    for clause in diff.split(" | "):
        clause = clause.strip().lstrip("*").strip()
        if clause.startswith("L ") and "->" in clause:
            il, _, lc = clause[2:].partition("->")
        elif clause.startswith("R ") and "->" in clause:
            ir, _, rc = clause[2:].partition("->")
    return (il.strip(), lc.strip(), ir.strip(), rc.strip())


if __name__ == "__main__":
    leaks = current_leaks()
    SNAPSHOT_PATH.write_text(format_snapshot(leaks))
    print(f"Wrote {len(leaks)} approved leak signatures to {SNAPSHOT_PATH.relative_to(ROOT)}")
