"""The classified isolation-leak snapshots: a bad-leak backlog and a benign census.

`doc/definitions/shaping-leakage.md` defines a *leak* as a cross-break shape difference and overlays a *bad* vs *benign* severity (see `tools/leak_classify.py`). This module runs the depth-4 sweep once, classifies every visible leak, and writes two files:

  * `test/bad-leak-backlog.txt` — the currently-known **bad** leaks (visible additive dangles). This is the autonomous fix loop's shrinking to-do list. The gate is asymmetric: a NEW bad signature is a regression and fails CI; a resolved one prints a re-bless notice. As the loop empties the backlog the gate converges to the spec's "zero bad."
  * `test/benign-leak-census.txt` — the **benign** leaks (subtractive trims, standalone-variant swaps, author cosmetic tucks). These are welcome — the faux-organic variation the script wants — so the gate is a symmetric census: any change is surfaced for review (re-bless), never a hard failure on its own.

Together the two files reconstruct the complete set of visible depth-4 leaks, partitioned by verdict. They replace the single undifferentiated `test/isolation-leak-snapshot.txt`.

Regenerate (bless the current state) with `make leak-snapshot`; check with `make test-leaks`.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEST_DIR = ROOT / "test"
BAD_BACKLOG_PATH = TEST_DIR / "bad-leak-backlog.txt"
BENIGN_CENSUS_PATH = TEST_DIR / "benign-leak-census.txt"

if str(TEST_DIR) not in sys.path:
    sys.path.insert(0, str(TEST_DIR))
if str(ROOT / "tools") not in sys.path:
    sys.path.insert(0, str(ROOT / "tools"))

import leak_classify  # noqa: E402
from build_check_html import IsolationLeakExample, Leak, find_visible_leaks  # noqa: E402

# Depth 4 is the sweet spot: it surfaces the four-letter-context leaks the depth-3 gate misses, at ≈1 min (vs. ≈44x that for depth 5). It is a strong regression gate, not a completeness proof — see doc/history/2026-06-03--leak-cleanup/leak-investigation-findings.md on why no fixed depth is provably complete.
MAX_LEN = 4

# A leak's structural identity, independent of which swept sequence happened to surface it first.
Signature = tuple[str, str, str, str]  # (isolated_left, left_chosen, isolated_right, right_chosen)


def _signature(leak: Leak) -> Signature:
    return (leak.isolated_left, leak.left_chosen, leak.isolated_right, leak.right_chosen)


def _example_label(example: IsolationLeakExample) -> str:
    fams = " ".join(f.removeprefix("qs") for f in example.families)
    return f"{fams} [break {example.break_index}]"


def current_visible_leaks(max_len: int = MAX_LEN) -> dict[Signature, str]:
    """Map each live visible-leak signature to a stable, human-readable example label. `find_visible_leaks` keys visibility on "any example renders a diff", so the set is independent of enumeration order and the chosen representative example is deterministic."""
    return {sig: _example_label(example) for sig, example in find_visible_leaks(max_len=max_len).items()}


def current_partition(max_len: int = MAX_LEN) -> tuple[dict[Signature, str], dict[Signature, str]]:
    """Partition the live visible leaks into (bad backlog, benign census) by the mechanical classifier. One sweep, classified in place — all live leaks here are visible (`diff`)."""
    force_bad = leak_classify.force_bad_signatures()
    force_benign = leak_classify.force_benign_signatures()
    bad: dict[Signature, str] = {}
    benign: dict[Signature, str] = {}
    for sig, label in current_visible_leaks(max_len).items():
        verdict = leak_classify.classify(sig, visible=True, force_bad=force_bad, force_benign=force_benign)
        (bad if verdict == "bad" else benign)[sig] = label
    return bad, benign


def _format_diff(leak_sig: Signature) -> str:
    # Both sides are always emitted (even the unchanged one) so the line round-trips back to the exact signature; a `*` marks the side that actually changed, for quick scanning.
    il, lc, ir, rc = leak_sig
    lmark = "*" if il != lc else " "
    rmark = "*" if ir != rc else " "
    return f"{lmark}L {il}->{lc} | {rmark}R {ir}->{rc}"


def format_snapshot(leaks: dict[Signature, str], *, title: str, blurb: str) -> str:
    lines = [
        f"# {title} Generated by `make leak-snapshot`; do not hand-edit.",
        f"# {blurb}",
        "# Each line: <example sequence> [break N] :: <glyph diff>. See doc/definitions/shaping-leakage.md.",
        f"# count: {len(leaks)}",
        "",
    ]
    for sig in sorted(leaks):
        lines.append(f"{leaks[sig]} :: {_format_diff(sig)}")
    return "\n".join(lines) + "\n"


def parse_snapshot(text: str) -> dict[Signature, str]:
    """Reconstruct signatures from a snapshot file. Keyed identity is the glyph diff after `::`; the example label is informational."""
    leaks: dict[Signature, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        label, _, diff = line.partition(" :: ")
        sig = _parse_diff(diff)
        leaks[sig] = label.strip()
    return leaks


def _parse_diff(diff: str) -> Signature:
    il = lc = ir = rc = ""
    for clause in diff.split(" | "):
        clause = clause.strip().lstrip("*").strip()
        if clause.startswith("L ") and "->" in clause:
            il, _, lc = clause[2:].partition("->")
        elif clause.startswith("R ") and "->" in clause:
            ir, _, rc = clause[2:].partition("->")
    return (il.strip(), lc.strip(), ir.strip(), rc.strip())


if __name__ == "__main__":
    bad, benign = current_partition()
    BAD_BACKLOG_PATH.write_text(
        format_snapshot(
            bad,
            title=f"Bad isolation-leak backlog at depth {MAX_LEN}.",
            blurb="Visible additive dangles the autonomous fix loop must drain. A NEW signature fails the gate; a resolved one is a re-bless notice.",
        )
    )
    BENIGN_CENSUS_PATH.write_text(
        format_snapshot(
            benign,
            title=f"Benign isolation-leak census at depth {MAX_LEN}.",
            blurb="The welcome faux-organic variation (subtractive trims, standalone-variant swaps, cosmetic tucks). Any change is surfaced for review.",
        )
    )
    print(
        f"Wrote {len(bad)} bad signatures to {BAD_BACKLOG_PATH.relative_to(ROOT)} "
        f"and {len(benign)} benign to {BENIGN_CENSUS_PATH.relative_to(ROOT)}"
    )
