"""Write the visible isolation leaks to a bad-leak backlog and a benign census.

`doc/definitions/shaping-leakage.md` defines a leak as a shape difference across a break, and `tools/leak_classify.py` labels each one bad or benign. Run as a script (`make leak-snapshot`), this module sweeps to depth 4, classifies every visible leak, and writes two files that together list all of them:

  * `site/bad-leak-backlog.txt`: the bad leaks (visible additive dangles). `test/test_isolation_leaks.py` fails on a bad leak missing from this file and only prints a notice for an entry that no longer occurs.
  * `site/benign-leak-census.txt`: the benign leaks (subtractive trims, standalone-variant swaps, and cosmetic tucks). `make test-leaks` fails on any difference from this file, so a reviewer sees each change before it is re-blessed.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEST_DIR = ROOT / "test"
SITE_DIR = ROOT / "site"
BAD_BACKLOG_PATH = SITE_DIR / "bad-leak-backlog.txt"
BENIGN_CENSUS_PATH = SITE_DIR / "benign-leak-census.txt"

if str(TEST_DIR) not in sys.path:
    sys.path.insert(0, str(TEST_DIR))
if str(ROOT / "tools") not in sys.path:
    sys.path.insert(0, str(ROOT / "tools"))

import leak_classify  # noqa: E402
from build_check_html import IsolationLeakExample, Leak, find_visible_leaks  # noqa: E402

# Depth 4 finds the leaks that need four letters of context, which the depth-3 check in `make test` misses. It takes about a minute, and depth 5 takes about 44 times as long. No fixed depth finds every leak (doc/history/2026-06-03--leak-cleanup/leak-investigation-findings.md).
MAX_LEN = 4

Signature = tuple[str, str, str, str]  # (isolated_left, left_chosen, isolated_right, right_chosen)


def _signature(leak: Leak) -> Signature:
    return (leak.isolated_left, leak.left_chosen, leak.isolated_right, leak.right_chosen)


def _example_label(example: IsolationLeakExample) -> str:
    fams = " ".join(f.removeprefix("qs") for f in example.families)
    return f"{fams} [break {example.break_index}]"


def current_visible_leaks(max_len: int = MAX_LEN) -> dict[Signature, str]:
    """Map each visible leak signature to a readable example label. The set does not depend on enumeration order, and the example chosen is deterministic (see `find_visible_leaks`)."""
    return {sig: _example_label(example) for sig, example in find_visible_leaks(max_len=max_len).items()}


def current_partition(max_len: int = MAX_LEN) -> tuple[dict[Signature, str], dict[Signature, str]]:
    """Split the visible leaks into (bad, benign) with `leak_classify.classify`, from one sweep."""
    force_bad = leak_classify.force_bad_signatures()
    force_benign = leak_classify.force_benign_signatures()
    bad: dict[Signature, str] = {}
    benign: dict[Signature, str] = {}
    for sig, label in current_visible_leaks(max_len).items():
        verdict = leak_classify.classify(sig, visible=True, force_bad=force_bad, force_benign=force_benign)
        (bad if verdict == "bad" else benign)[sig] = label
    return bad, benign


def _format_diff(leak_sig: Signature) -> str:
    # Both sides are written, even an unchanged one, so that `parse_snapshot` can rebuild the signature. A `*` marks each side that changed.
    il, lc, ir, rc = leak_sig
    lmark = "*" if il != lc else " "
    rmark = "*" if ir != rc else " "
    return f"{lmark}L {il}->{lc} | {rmark}R {ir}->{rc}"


def format_snapshot(leaks: dict[Signature, str], *, title: str, blurb: str) -> str:
    lines = [
        f"# {title} Generated by `make leak-snapshot`; do not hand-edit.",
        f"# {blurb}",
        "# Each line: <example sequence> [break N] :: <glyph diff>. See doc/definitions/shaping-leakage.md.",
        f"# count: {len(leaks)}",
        "",
    ]
    for sig in sorted(leaks):
        lines.append(f"{leaks[sig]} :: {_format_diff(sig)}")
    return "\n".join(lines) + "\n"


def parse_snapshot(text: str) -> dict[Signature, str]:
    """Map each signature in a snapshot file, parsed from the glyph diff after `::`, to its example label."""
    leaks: dict[Signature, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        label, _, diff = line.partition(" :: ")
        sig = _parse_diff(diff)
        leaks[sig] = label.strip()
    return leaks


def _parse_diff(diff: str) -> Signature:
    il = lc = ir = rc = ""
    for clause in diff.split(" | "):
        clause = clause.strip().lstrip("*").strip()
        if clause.startswith("L ") and "->" in clause:
            il, _, lc = clause[2:].partition("->")
        elif clause.startswith("R ") and "->" in clause:
            ir, _, rc = clause[2:].partition("->")
    return (il.strip(), lc.strip(), ir.strip(), rc.strip())


if __name__ == "__main__":
    bad, benign = current_partition()
    BAD_BACKLOG_PATH.write_text(
        format_snapshot(
            bad,
            title=f"Bad isolation-leak backlog at depth {MAX_LEN}.",
            blurb="Visible additive dangles the autonomous fix loop must drain. A NEW signature fails the gate; a resolved one is a re-bless notice.",
        )
    )
    BENIGN_CENSUS_PATH.write_text(
        format_snapshot(
            benign,
            title=f"Benign isolation-leak census at depth {MAX_LEN}.",
            blurb="The welcome faux-organic variation (subtractive trims, standalone-variant swaps, cosmetic tucks). Any change is surfaced for review.",
        )
    )
    print(
        f"Wrote {len(bad)} bad signatures to {BAD_BACKLOG_PATH.relative_to(ROOT)} "
        f"and {len(benign)} benign to {BENIGN_CENSUS_PATH.relative_to(ROOT)}"
    )
